USE SOPRA_HRIS;

CREATE TABLE Locations (
	LocationID BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255),
	DateIn DATETIME DEFAULT CURRENT_TIMESTAMP,
	DateUp DATETIME,
	UserIn BIGINT,
	UserUp BIGINT,
	IsDeleted BIT DEFAULT 0
);